name: tests
run-name: Testing
on: [push]
jobs:
  test-objects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test_objects

  test-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test_list
  
  test-queue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test_queue

  test-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test_stack

  test-tree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test_tree

  test-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test_graph

  test-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test_hash
